export const SETSONGDETAILDATA = 'SETSONGDETAILDATA'
export const SETSONGLISTDATA= 'SETSONGLISTDATA'
export const SETCURRENTSONGINDEX= 'SETCURRENTSONGINDEX'
export const SETPLAYSTATUS= 'SETPLAYSTATUS'
export const SETLRCARR = 'SETLRCARR'

