export const SETBANNERDATA = 'SETBANNERDATA'
export const SETHOTRECOMMEND = 'SETHOTRECOMMEND'
export const SETNEWALBUM = 'SETNEWALBUM'
export const SETHOTRANK = 'SETHOTRANK'
export const SETMINERANK = 'SETMINERANK'
export const SETNEWRANK = 'SETNEWRANK'






